---
# Enable Aegir to access as a remote user.

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific tasks.
  include: "{{ ansible_os_family }}.yml"

- name: Add aegir user to sudoers to reload apache
  lineinfile:
    dest: '{{ sudoers_file_path }}'
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=NOPASSWD: {{ apache_control }}'
    state: present
    validate: 'visudo -cf %s'
    create: yes
  with_items:
    - aegir

- name: Post Install on RedHat
  include: "RedHat-post.yml"
  when: ansible_os_family == "RedHat"

- name: Post Install on Debian
  include: "Debian-post.yml"
  when: ansible_os_family == "Debian"
