---
# Enable Aegir to access as a remote user.

- name: Symbolic link to Aegir's Apache Config
  when: ansible_os_family == "Debian"
  file:
    src: /var/aegir/config/apache.conf
    # For Debian, apache_conf_path == '/etc/apache2'
    dest: "{{ apache_conf_path }}/conf-enabled/aegir.conf"
    state: link
    force: yes

- name: Symbolic link to Aegir's Apache Config
  when: ansible_os_family == "RedHat"
  file:
    src: /var/aegir/config/apache.conf
    # For RedHat, apache_conf_path == '/etc/httpd/conf.d'
    dest: "{{ apache_conf_path }}/aegir.conf"
    state: link
    force: yes

- name: Add aegir user to sudoers to reload apache
  lineinfile:
    dest: '{{ sudoers_file_path }}'
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=NOPASSWD: {{ apache_control }}'
    state: present
    validate: 'visudo -cf %s'
  with_items:
    - aegir
